SuperStrict

Import "SDL3/include/*.h"
Import "SDL3/src/*.h"
Import "SDL3/include/build_config/*.h"
Import "SDL3/src/hidapi/hidapi/*.h"
Import "SDL3/src/hidapi/mac/*.h"
Import "SDL3/src/video/khronos/*.h"

Import "SDL3/src/atomic/SDL_atomic.c"
Import "SDL3/src/atomic/SDL_spinlock.c"
Import "SDL3/src/audio/aaudio/SDL_aaudio.c"
Import "SDL3/src/audio/alsa/SDL_alsa_audio.c"
Import "SDL3/src/audio/directsound/SDL_directsound.c"
Import "SDL3/src/audio/disk/SDL_diskaudio.c"
Import "SDL3/src/audio/dsp/SDL_dspaudio.c"
Import "SDL3/src/audio/dummy/SDL_dummyaudio.c"
' Import "SDL3/src/audio/emscripten/SDL_emscriptenaudio.c"
Import "SDL3/src/audio/jack/SDL_jackaudio.c"
Import "SDL3/src/audio/n3ds/SDL_n3dsaudio.c"
Import "SDL3/src/audio/netbsd/SDL_netbsdaudio.c"
Import "SDL3/src/audio/openslES/SDL_openslES.c"
Import "SDL3/src/audio/pipewire/SDL_pipewire.c"
'Import "SDL3/src/audio/ps2/SDL_ps2audio.c"
'Import "SDL3/src/audio/psp/SDL_pspaudio.c"
Import "SDL3/src/audio/pulseaudio/SDL_pulseaudio.c"
Import "SDL3/src/audio/qnx/SDL_qsa_audio.c"
Import "SDL3/src/audio/SDL_audio.c"
Import "SDL3/src/audio/SDL_audiocvt.c"
Import "SDL3/src/audio/SDL_audiodev.c"
Import "SDL3/src/audio/SDL_audioqueue.c"
Import "SDL3/src/audio/SDL_audioresample.c"
Import "SDL3/src/audio/SDL_audiotypecvt.c"
Import "SDL3/src/audio/SDL_mixer.c"
Import "SDL3/src/audio/SDL_wave.c"
Import "SDL3/src/audio/sndio/SDL_sndioaudio.c"
' Import "SDL3/src/audio/vita/SDL_vitaaudio.c"
Import "SDL3/src/audio/wasapi/SDL_wasapi.c"
Import "SDL3/src/camera/coremedia/SDL_camera_coremedia.m"
Import "SDL3/src/camera/dummy/SDL_camera_dummy.c"
' Import "SDL3/src/camera/emscripten/SDL_camera_emscripten.c"
Import "SDL3/src/camera/mediafoundation/SDL_camera_mediafoundation.c"
Import "SDL3/src/camera/pipewire/SDL_camera_pipewire.c"
Import "SDL3/src/camera/SDL_camera.c"
Import "SDL3/src/camera/v4l2/SDL_camera_v4l2.c"
' Import "SDL3/src/camera/vita/SDL_camera_vita.c"
' Import "SDL3/src/core/freebsd/SDL_evdev_kbd_freebsd.c"
'Import "SDL3/src/core/linux/SDL_dbus.c"
'Import "SDL3/src/core/linux/SDL_evdev_capabilities.c"
'Import "SDL3/src/core/linux/SDL_evdev_kbd.c"
'Import "SDL3/src/core/linux/SDL_evdev.c"
'Import "SDL3/src/core/linux/SDL_fcitx.c"
'Import "SDL3/src/core/linux/SDL_ibus.c"
'Import "SDL3/src/core/linux/SDL_ime.c"
'Import "SDL3/src/core/linux/SDL_system_theme.c"
'Import "SDL3/src/core/linux/SDL_threadprio.c"
'Import "SDL3/src/core/linux/SDL_udev.c"
'Import "SDL3/src/core/openbsd/SDL_wscons_kbd.c"
'Import "SDL3/src/core/openbsd/SDL_wscons_mouse.c"
Import "SDL3/src/core/SDL_core_unsupported.c"
Import "SDL3/src/core/unix/SDL_appid.c"
Import "SDL3/src/core/unix/SDL_poll.c"
Import "SDL3/src/cpuinfo/SDL_cpuinfo.c"
Import "SDL3/src/dialog/cocoa/SDL_cocoadialog.m"
Import "SDL3/src/dialog/dummy/SDL_dummydialog.c"
Import "SDL3/src/dialog/SDL_dialog_utils.c"
Import "SDL3/src/dialog/SDL_dialog.c"
Import "SDL3/src/dialog/unix/SDL_portaldialog.c"
Import "SDL3/src/dialog/unix/SDL_unixdialog.c"
Import "SDL3/src/dialog/unix/SDL_zenitydialog.c"
Import "SDL3/src/dynapi/SDL_dynapi.c"
Import "SDL3/src/events/imKStoUCS.c"
Import "SDL3/src/events/SDL_categories.c"
Import "SDL3/src/events/SDL_clipboardevents.c"
Import "SDL3/src/events/SDL_displayevents.c"
Import "SDL3/src/events/SDL_dropevents.c"
Import "SDL3/src/events/SDL_events.c"
Import "SDL3/src/events/SDL_eventwatch.c"
Import "SDL3/src/events/SDL_keyboard.c"
Import "SDL3/src/events/SDL_keymap.c"
Import "SDL3/src/events/SDL_keysym_to_keycode.c"
Import "SDL3/src/events/SDL_keysym_to_scancode.c"
Import "SDL3/src/events/SDL_mouse.c"
Import "SDL3/src/events/SDL_pen.c"
Import "SDL3/src/events/SDL_quit.c"
Import "SDL3/src/events/SDL_scancode_tables.c"
Import "SDL3/src/events/SDL_touch.c"
Import "SDL3/src/filesystem/cocoa/SDL_sysfilesystem.m"
Import "SDL3/src/filesystem/dummy/SDL_sysfilesystem.c"
Import "SDL3/src/filesystem/dummy/SDL_sysfsops.c"
' Import "SDL3/src/filesystem/emscripten/SDL_sysfilesystem.c"
' Import "SDL3/src/filesystem/n3ds/SDL_sysfilesystem.c"
Import "SDL3/src/filesystem/posix/SDL_sysfsops.c"
' Import "SDL3/src/filesystem/ps2/SDL_sysfilesystem.c"
' Import "SDL3/src/filesystem/psp/SDL_sysfilesystem.c"
' Import "SDL3/src/filesystem/riscos/SDL_sysfilesystem.c"
Import "SDL3/src/filesystem/SDL_filesystem.c"
Import "SDL3/src/filesystem/unix/SDL_sysfilesystem.c"
' Import "SDL3/src/filesystem/vita/SDL_sysfilesystem.c"
Import "SDL3/src/gpu/d3d12/SDL_gpu_d3d12.c"
Import "SDL3/src/gpu/metal/SDL_gpu_metal.m"
Import "SDL3/src/gpu/SDL_gpu.c"
Import "SDL3/src/gpu/vulkan/SDL_gpu_vulkan.c"
'Import "SDL3/src/haptic/dummy/SDL_syshaptic.c"
'Import "SDL3/src/haptic/linux/SDL_syshaptic.c"
Import "SDL3/src/haptic/SDL_haptic.c"
Import "SDL3/src/hidapi/hidtest/test.c"
'Import "SDL3/src/hidapi/libusb/hid.c"
'Import "SDL3/src/hidapi/linux/hid.c"
'Import "SDL3/src/hidapi/netbsd/hid.c"
Import "SDL3/src/hidapi/SDL_hidapi.c"
'Import "SDL3/src/hidapi/testgui/mac_support_cocoa.m"
Import "SDL3/src/io/generic/SDL_asyncio_generic.c"
Import "SDL3/src/io/io_uring/SDL_asyncio_liburing.c"
' Import "SDL3/src/io/n3ds/SDL_iostreamromfs.c"
Import "SDL3/src/io/SDL_asyncio.c"
Import "SDL3/src/io/SDL_iostream.c"
'Import "SDL3/src/joystick/apple/SDL_mfijoystick.m"
Import "SDL3/src/joystick/bsd/SDL_bsdjoystick.c"
Import "SDL3/src/joystick/controller_type.c"
Import "SDL3/src/joystick/dummy/SDL_sysjoystick.c"
' Import "SDL3/src/joystick/emscripten/SDL_sysjoystick.c"
' Import "SDL3/src/joystick/gdk/SDL_gameinputjoystick.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_combined.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_gamecube.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_luna.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_ps3.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_ps4.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_ps5.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_rumble.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_shield.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_stadia.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_steam_hori.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_steam.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_steamdeck.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_switch.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_wii.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_xbox360.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_xbox360w.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapi_xboxone.c"
Import "SDL3/src/joystick/hidapi/SDL_hidapijoystick.c"
'Import "SDL3/src/joystick/linux/SDL_sysjoystick.c"
' Import "SDL3/src/joystick/n3ds/SDL_sysjoystick.c"
'Import "SDL3/src/joystick/ps2/SDL_sysjoystick.c"
'Import "SDL3/src/joystick/psp/SDL_sysjoystick.c"
Import "SDL3/src/joystick/SDL_gamepad.c"
Import "SDL3/src/joystick/SDL_joystick.c"
Import "SDL3/src/joystick/SDL_steam_virtual_gamepad.c"
Import "SDL3/src/joystick/virtual/SDL_virtualjoystick.c"
' Import "SDL3/src/joystick/vita/SDL_sysjoystick.c"
Import "SDL3/src/libm/e_atan2.c"
Import "SDL3/src/libm/e_exp.c"
Import "SDL3/src/libm/e_fmod.c"
Import "SDL3/src/libm/e_log.c"
Import "SDL3/src/libm/e_log10.c"
Import "SDL3/src/libm/e_pow.c"
Import "SDL3/src/libm/e_rem_pio2.c"
Import "SDL3/src/libm/e_sqrt.c"
Import "SDL3/src/libm/k_cos.c"
Import "SDL3/src/libm/k_rem_pio2.c"
Import "SDL3/src/libm/k_sin.c"
Import "SDL3/src/libm/k_tan.c"
Import "SDL3/src/libm/s_atan.c"
Import "SDL3/src/libm/s_copysign.c"
Import "SDL3/src/libm/s_cos.c"
Import "SDL3/src/libm/s_fabs.c"
Import "SDL3/src/libm/s_floor.c"
Import "SDL3/src/libm/s_isinf.c"
Import "SDL3/src/libm/s_isinff.c"
Import "SDL3/src/libm/s_isnan.c"
Import "SDL3/src/libm/s_isnanf.c"
Import "SDL3/src/libm/s_modf.c"
Import "SDL3/src/libm/s_scalbn.c"
Import "SDL3/src/libm/s_sin.c"
Import "SDL3/src/libm/s_tan.c"
Import "SDL3/src/loadso/dlopen/SDL_sysloadso.c"
Import "SDL3/src/loadso/dummy/SDL_sysloadso.c"
Import "SDL3/src/locale/dummy/SDL_syslocale.c"
' Import "SDL3/src/locale/emscripten/SDL_syslocale.c"
' Import "SDL3/src/locale/n3ds/SDL_syslocale.c"
' Import "SDL3/src/locale/psp/SDL_syslocale.c"
Import "SDL3/src/locale/SDL_locale.c"
Import "SDL3/src/locale/unix/SDL_syslocale.c"
' Import "SDL3/src/locale/vita/SDL_syslocale.c"
' Import "SDL3/src/main/emscripten/SDL_sysmain_callbacks.c"
' Import "SDL3/src/main/emscripten/SDL_sysmain_runapp.c"
Import "SDL3/src/main/generic/SDL_sysmain_callbacks.c"
' Import "SDL3/src/main/n3ds/SDL_sysmain_runapp.c"
'Import "SDL3/src/main/ps2/SDL_sysmain_runapp.c"
'Import "SDL3/src/main/psp/SDL_sysmain_runapp.c"
Import "SDL3/src/main/SDL_main_callbacks.c"
Import "SDL3/src/main/SDL_runapp.c"
Import "SDL3/src/misc/dummy/SDL_sysurl.c"
' Import "SDL3/src/misc/emscripten/SDL_sysurl.c"
' Import "SDL3/src/misc/riscos/SDL_sysurl.c"
Import "SDL3/src/misc/SDL_url.c"
Import "SDL3/src/misc/unix/SDL_sysurl.c"
' Import "SDL3/src/misc/vita/SDL_sysurl.c"
' Import "SDL3/src/power/emscripten/SDL_syspower.c"
'Import "SDL3/src/power/linux/SDL_syspower.c"
' Import "SDL3/src/power/n3ds/SDL_syspower.c"
' Import "SDL3/src/power/psp/SDL_syspower.c"
Import "SDL3/src/power/SDL_power.c"
Import "SDL3/src/power/uikit/SDL_syspower.m"
' Import "SDL3/src/power/vita/SDL_syspower.c"
Import "SDL3/src/process/dummy/SDL_dummyprocess.c"
Import "SDL3/src/process/posix/SDL_posixprocess.c"
Import "SDL3/src/process/SDL_process.c"
Import "SDL3/src/render/gpu/SDL_pipeline_gpu.c"
Import "SDL3/src/render/gpu/SDL_render_gpu.c"
Import "SDL3/src/render/gpu/SDL_shaders_gpu.c"
Import "SDL3/src/render/opengl/SDL_render_gl.c"
Import "SDL3/src/render/opengl/SDL_shaders_gl.c"
Import "SDL3/src/render/opengles2/SDL_render_gles2.c"
Import "SDL3/src/render/opengles2/SDL_shaders_gles2.c"
'Import "SDL3/src/render/ps2/SDL_render_ps2.c"
'Import "SDL3/src/render/psp/SDL_render_psp.c"
' Import "SDL3/src/render/SDL_d3dmath.c"
Import "SDL3/src/render/SDL_render_unsupported.c"
Import "SDL3/src/render/SDL_render.c"
Import "SDL3/src/render/SDL_yuv_sw.c"
Import "SDL3/src/render/software/SDL_blendfillrect.c"
Import "SDL3/src/render/software/SDL_blendline.c"
Import "SDL3/src/render/software/SDL_blendpoint.c"
Import "SDL3/src/render/software/SDL_drawline.c"
Import "SDL3/src/render/software/SDL_drawpoint.c"
Import "SDL3/src/render/software/SDL_render_sw.c"
' Import "SDL3/src/render/software/SDL_rotate.c"
Import "SDL3/src/render/software/SDL_triangle.c"
' Import "SDL3/src/render/vitagxm/SDL_render_vita_gxm_memory.c"
' Import "SDL3/src/render/vitagxm/SDL_render_vita_gxm_tools.c"
' Import "SDL3/src/render/vitagxm/SDL_render_vita_gxm.c"
Import "SDL3/src/render/vulkan/SDL_render_vulkan.c"
Import "SDL3/src/render/vulkan/SDL_shaders_vulkan.c"
Import "SDL3/src/SDL_assert.c"
Import "SDL3/src/SDL_error.c"
Import "SDL3/src/SDL_guid.c"
Import "SDL3/src/SDL_hashtable.c"
Import "SDL3/src/SDL_hints.c"
Import "SDL3/src/SDL_list.c"
Import "SDL3/src/SDL_log.c"
Import "SDL3/src/SDL_properties.c"
Import "SDL3/src/SDL_utils.c"
Import "SDL3/src/SDL.c"
Import "SDL3/src/sensor/dummy/SDL_dummysensor.c"
' Import "SDL3/src/sensor/n3ds/SDL_n3dssensor.c"
Import "SDL3/src/sensor/SDL_sensor.c"
' Import "SDL3/src/sensor/vita/SDL_vitasensor.c"
Import "SDL3/src/stdlib/SDL_crc16.c"
Import "SDL3/src/stdlib/SDL_crc32.c"
Import "SDL3/src/stdlib/SDL_getenv.c"
Import "SDL3/src/stdlib/SDL_iconv.c"
Import "SDL3/src/stdlib/SDL_malloc.c"
Import "SDL3/src/stdlib/SDL_memcpy.c"
Import "SDL3/src/stdlib/SDL_memmove.c"
' Import "SDL3/src/stdlib/SDL_memset.c"
Import "SDL3/src/stdlib/SDL_mslibc.c"
Import "SDL3/src/stdlib/SDL_murmur3.c"
Import "SDL3/src/stdlib/SDL_qsort.c"
Import "SDL3/src/stdlib/SDL_random.c"
Import "SDL3/src/stdlib/SDL_stdlib.c"
Import "SDL3/src/stdlib/SDL_string.c"
Import "SDL3/src/stdlib/SDL_strtokr.c"
Import "SDL3/src/storage/generic/SDL_genericstorage.c"
Import "SDL3/src/storage/SDL_storage.c"
Import "SDL3/src/storage/steam/SDL_steamstorage.c"
' Import "SDL3/src/test/SDL_test_assert.c"
' Import "SDL3/src/test/SDL_test_common.c"
' Import "SDL3/src/test/SDL_test_compare.c"
' Import "SDL3/src/test/SDL_test_crc32.c"
' Import "SDL3/src/test/SDL_test_font.c"
' Import "SDL3/src/test/SDL_test_fuzzer.c"
' Import "SDL3/src/test/SDL_test_harness.c"
' Import "SDL3/src/test/SDL_test_log.c"
' Import "SDL3/src/test/SDL_test_md5.c"
' Import "SDL3/src/test/SDL_test_memory.c"
Import "SDL3/src/thread/generic/SDL_syscond.c"
Import "SDL3/src/thread/generic/SDL_sysmutex.c"
Import "SDL3/src/thread/generic/SDL_sysrwlock.c"
Import "SDL3/src/thread/generic/SDL_syssem.c"
Import "SDL3/src/thread/generic/SDL_systhread.c"
Import "SDL3/src/thread/generic/SDL_systls.c"
Import "SDL3/src/thread/n3ds/SDL_sysmutex.c"
Import "SDL3/src/thread/n3ds/SDL_syssem.c"
Import "SDL3/src/thread/n3ds/SDL_systhread.c"
'Import "SDL3/src/thread/ps2/SDL_syssem.c"
'Import "SDL3/src/thread/ps2/SDL_systhread.c"
'Import "SDL3/src/thread/psp/SDL_sysmutex.c"
'Import "SDL3/src/thread/psp/SDL_syssem.c"
'Import "SDL3/src/thread/psp/SDL_systhread.c"
Import "SDL3/src/thread/pthread/SDL_syscond.c"
Import "SDL3/src/thread/pthread/SDL_sysmutex.c"
Import "SDL3/src/thread/pthread/SDL_sysrwlock.c"
Import "SDL3/src/thread/pthread/SDL_syssem.c"
Import "SDL3/src/thread/pthread/SDL_systhread.c"
Import "SDL3/src/thread/pthread/SDL_systls.c"
Import "SDL3/src/thread/SDL_thread.c"
Import "SDL3/src/thread/vita/SDL_sysmutex.c"
Import "SDL3/src/thread/vita/SDL_syssem.c"
Import "SDL3/src/thread/vita/SDL_systhread.c"
Import "SDL3/src/time/n3ds/SDL_systime.c"
'Import "SDL3/src/time/ps2/SDL_systime.c"
'Import "SDL3/src/time/psp/SDL_systime.c"
Import "SDL3/src/time/SDL_time.c"
Import "SDL3/src/time/unix/SDL_systime.c"
Import "SDL3/src/time/vita/SDL_systime.c"
Import "SDL3/src/timer/n3ds/SDL_systimer.c"
'Import "SDL3/src/timer/ps2/SDL_systimer.c"
'Import "SDL3/src/timer/psp/SDL_systimer.c"
Import "SDL3/src/timer/SDL_timer.c"
Import "SDL3/src/timer/unix/SDL_systimer.c"
' Import "SDL3/src/timer/vita/SDL_systimer.c"
Import "SDL3/src/tray/dummy/SDL_tray.c"
Import "SDL3/src/tray/SDL_tray_utils.c"
Import "SDL3/src/tray/unix/SDL_tray.c"


Import "SDL3/src/video/dummy/SDL_nullevents.c"
Import "SDL3/src/video/dummy/SDL_nullframebuffer.c"
Import "SDL3/src/video/dummy/SDL_nullvideo.c"
' Import "SDL3/src/video/emscripten/SDL_emscriptenevents.c"
' Import "SDL3/src/video/emscripten/SDL_emscriptenframebuffer.c"
' Import "SDL3/src/video/emscripten/SDL_emscriptenmouse.c"
' Import "SDL3/src/video/emscripten/SDL_emscriptenopengles.c"
' Import "SDL3/src/video/emscripten/SDL_emscriptenvideo.c"
' Import "SDL3/src/video/kmsdrm/SDL_kmsdrmdyn.c"
' Import "SDL3/src/video/kmsdrm/SDL_kmsdrmevents.c"
' Import "SDL3/src/video/kmsdrm/SDL_kmsdrmmouse.c"
' Import "SDL3/src/video/kmsdrm/SDL_kmsdrmopengles.c"
' Import "SDL3/src/video/kmsdrm/SDL_kmsdrmvideo.c"
' Import "SDL3/src/video/kmsdrm/SDL_kmsdrmvulkan.c"
' Import "SDL3/src/video/n3ds/SDL_n3dsevents.c"
' Import "SDL3/src/video/n3ds/SDL_n3dsframebuffer.c"
' Import "SDL3/src/video/n3ds/SDL_n3dsswkb.c"
' Import "SDL3/src/video/n3ds/SDL_n3dstouch.c"
' Import "SDL3/src/video/n3ds/SDL_n3dsvideo.c"
Import "SDL3/src/video/offscreen/SDL_offscreenevents.c"
Import "SDL3/src/video/offscreen/SDL_offscreenframebuffer.c"
Import "SDL3/src/video/offscreen/SDL_offscreenopengles.c"
Import "SDL3/src/video/offscreen/SDL_offscreenvideo.c"
Import "SDL3/src/video/offscreen/SDL_offscreenvulkan.c"
Import "SDL3/src/video/offscreen/SDL_offscreenwindow.c"
Import "SDL3/src/video/openvr/SDL_openvrvideo.c"
'Import "SDL3/src/video/ps2/SDL_ps2video.c"
'Import "SDL3/src/video/psp/SDL_pspevents.c"
'Import "SDL3/src/video/psp/SDL_pspgl.c"
'Import "SDL3/src/video/psp/SDL_pspmouse.c"
'Import "SDL3/src/video/psp/SDL_pspvideo.c"
' Import "SDL3/src/video/qnx/SDL_qnxgl.c"
' Import "SDL3/src/video/qnx/SDL_qnxkeyboard.c"
' Import "SDL3/src/video/qnx/SDL_qnxvideo.c"
' Import "SDL3/src/video/raspberry/SDL_rpievents.c"
' Import "SDL3/src/video/raspberry/SDL_rpimouse.c"
' Import "SDL3/src/video/raspberry/SDL_rpiopengles.c"
' Import "SDL3/src/video/raspberry/SDL_rpivideo.c"
' Import "SDL3/src/video/riscos/SDL_riscosevents.c"
' Import "SDL3/src/video/riscos/SDL_riscosframebuffer.c"
' Import "SDL3/src/video/riscos/SDL_riscosmessagebox.c"
' Import "SDL3/src/video/riscos/SDL_riscosmodes.c"
' Import "SDL3/src/video/riscos/SDL_riscosmouse.c"
' Import "SDL3/src/video/riscos/SDL_riscosvideo.c"
' Import "SDL3/src/video/riscos/SDL_riscoswindow.c"
Import "SDL3/src/video/SDL_blit_0.c"
Import "SDL3/src/video/SDL_blit_1.c"
Import "SDL3/src/video/SDL_blit_A.c"
Import "SDL3/src/video/SDL_blit_auto.c"
Import "SDL3/src/video/SDL_blit_copy.c"
Import "SDL3/src/video/SDL_blit_N.c"
Import "SDL3/src/video/SDL_blit_slow.c"
Import "SDL3/src/video/SDL_blit.c"
Import "SDL3/src/video/SDL_bmp.c"
Import "SDL3/src/video/SDL_clipboard.c"
' Import "SDL3/src/video/SDL_egl.c"
Import "SDL3/src/video/SDL_fillrect.c"
Import "SDL3/src/video/SDL_pixels.c"
Import "SDL3/src/video/SDL_rect.c"
Import "SDL3/src/video/SDL_RLEaccel.c"
Import "SDL3/src/video/SDL_stb.c"
Import "SDL3/src/video/SDL_stretch.c"
Import "SDL3/src/video/SDL_surface.c"
Import "SDL3/src/video/SDL_video_unsupported.c"
Import "SDL3/src/video/SDL_video.c"
Import "SDL3/src/video/SDL_vulkan_utils.c"
Import "SDL3/src/video/SDL_yuv.c"
' Import "SDL3/src/video/vita/SDL_vitaframebuffer.c"
' Import "SDL3/src/video/vita/SDL_vitagl_pvr.c"
' Import "SDL3/src/video/vita/SDL_vitagles_pvr.c"
' Import "SDL3/src/video/vita/SDL_vitagles.c"
' Import "SDL3/src/video/vita/SDL_vitakeyboard.c"
' Import "SDL3/src/video/vita/SDL_vitamessagebox.c"
' Import "SDL3/src/video/vita/SDL_vitamouse.c"
' Import "SDL3/src/video/vita/SDL_vitatouch.c"
' Import "SDL3/src/video/vita/SDL_vitavideo.c"
' Import "SDL3/src/video/vivante/SDL_vivanteopengles.c"
' Import "SDL3/src/video/vivante/SDL_vivanteplatform.c"
' Import "SDL3/src/video/vivante/SDL_vivantevideo.c"
' Import "SDL3/src/video/vivante/SDL_vivantevulkan.c"
' Import "SDL3/src/video/wayland/SDL_waylandclipboard.c"
' Import "SDL3/src/video/wayland/SDL_waylandcolor.c"
' Import "SDL3/src/video/wayland/SDL_waylanddatamanager.c"
' Import "SDL3/src/video/wayland/SDL_waylanddyn.c"
' Import "SDL3/src/video/wayland/SDL_waylandevents.c"
' Import "SDL3/src/video/wayland/SDL_waylandkeyboard.c"
' Import "SDL3/src/video/wayland/SDL_waylandmessagebox.c"
' Import "SDL3/src/video/wayland/SDL_waylandmouse.c"
' Import "SDL3/src/video/wayland/SDL_waylandopengles.c"
' Import "SDL3/src/video/wayland/SDL_waylandshmbuffer.c"
' Import "SDL3/src/video/wayland/SDL_waylandvideo.c"
' Import "SDL3/src/video/wayland/SDL_waylandvulkan.c"
' Import "SDL3/src/video/wayland/SDL_waylandwindow.c"
' Import "SDL3/src/video/x11/edid-parse.c"
' Import "SDL3/src/video/x11/SDL_x11clipboard.c"
' Import "SDL3/src/video/x11/SDL_x11dyn.c"
' Import "SDL3/src/video/x11/SDL_x11events.c"
' Import "SDL3/src/video/x11/SDL_x11framebuffer.c"
' Import "SDL3/src/video/x11/SDL_x11keyboard.c"
' Import "SDL3/src/video/x11/SDL_x11messagebox.c"
' Import "SDL3/src/video/x11/SDL_x11modes.c"
' Import "SDL3/src/video/x11/SDL_x11mouse.c"
' Import "SDL3/src/video/x11/SDL_x11opengl.c"
' Import "SDL3/src/video/x11/SDL_x11opengles.c"
' Import "SDL3/src/video/x11/SDL_x11pen.c"
' Import "SDL3/src/video/x11/SDL_x11settings.c"
' Import "SDL3/src/video/x11/SDL_x11shape.c"
' Import "SDL3/src/video/x11/SDL_x11touch.c"
' Import "SDL3/src/video/x11/SDL_x11video.c"
' Import "SDL3/src/video/x11/SDL_x11vulkan.c"
' Import "SDL3/src/video/x11/SDL_x11window.c"
' Import "SDL3/src/video/x11/SDL_x11xfixes.c"
' Import "SDL3/src/video/x11/SDL_x11xinput2.c"
' Import "SDL3/src/video/x11/SDL_x11xsync.c"
' Import "SDL3/src/video/x11/xsettings-client.c"
Import "SDL3/src/video/yuv2rgb/yuv_rgb_lsx.c"
Import "SDL3/src/video/yuv2rgb/yuv_rgb_sse.c"
Import "SDL3/src/video/yuv2rgb/yuv_rgb_std.c"


?win32
Import "SDL3/src/core/windows/pch.c"
Import "SDL3/src/core/windows/SDL_gameinput.cpp"
Import "SDL3/src/core/windows/SDL_hid.c"
Import "SDL3/src/core/windows/SDL_immdevice.c"
Import "SDL3/src/core/windows/SDL_windows.c"
Import "SDL3/src/core/windows/SDL_xinput.c"

Import "SDL3/src/dialog/windows/SDL_windowsdialog.c"
Import "SDL3/src/events/SDL_windowevents.c"
Import "SDL3/src/filesystem/windows/SDL_sysfilesystem.c"
Import "SDL3/src/filesystem/windows/SDL_sysfsops.c"
Import "SDL3/src/haptic/windows/SDL_dinputhaptic.c"
Import "SDL3/src/haptic/windows/SDL_windowshaptic.c"
Import "SDL3/src/hidapi/windows/hid.c"
Import "SDL3/src/hidapi/windows/hidapi_descriptor_reconstruct.c"
Import "SDL3/src/hidapi/windows/pp_data_dump/pp_data_dump.c"
Import "SDL3/src/hidapi/windows/test/hid_report_reconstructor_test.c"
Import "SDL3/src/io/windows/SDL_asyncio_windows_ioring.c"
Import "SDL3/src/joystick/windows/SDL_dinputjoystick.c"
Import "SDL3/src/joystick/windows/SDL_rawinputjoystick.c"
Import "SDL3/src/joystick/windows/SDL_windows_gaming_input.c"
Import "SDL3/src/joystick/windows/SDL_windowsjoystick.c"
Import "SDL3/src/joystick/windows/SDL_xinputjoystick.c"
Import "SDL3/src/loadso/windows/SDL_sysloadso.c"
Import "SDL3/src/locale/windows/SDL_syslocale.c"
Import "SDL3/src/main/windows/SDL_sysmain_runapp.c"
Import "SDL3/src/misc/windows/SDL_sysurl.c"
Import "SDL3/src/power/windows/SDL_syspower.c"
Import "SDL3/src/process/windows/SDL_windowsprocess.c"

Import "SDL3/src/render/direct3d/SDL_render_d3d.c"
Import "SDL3/src/render/direct3d/SDL_shaders_d3d.c"
Import "SDL3/src/render/direct3d11/SDL_render_d3d11.c"
Import "SDL3/src/render/direct3d11/SDL_shaders_d3d11.c"
Import "SDL3/src/render/direct3d12/SDL_render_d3d12.c"
Import "SDL3/src/render/direct3d12/SDL_shaders_d3d12.c"

Import "SDL3/src/sensor/windows/SDL_windowssensor.c"
Import "SDL3/src/time/windows/SDL_systime.c"
Import "SDL3/src/timer/windows/SDL_systimer.c"

Import "SDL3/src/thread/windows/SDL_syscond_cv.c"
Import "SDL3/src/thread/windows/SDL_sysmutex.c"
Import "SDL3/src/thread/windows/SDL_sysrwlock_srw.c"
Import "SDL3/src/thread/windows/SDL_syssem.c"
Import "SDL3/src/thread/windows/SDL_systhread.c"
Import "SDL3/src/thread/windows/SDL_systls.c"

Import "SDL3/src/tray/windows/SDL_tray.c"

Import "SDL3/src/video/windows/SDL_windowsclipboard.c"
Import "SDL3/src/video/windows/SDL_windowsevents.c"
Import "SDL3/src/video/windows/SDL_windowsframebuffer.c"
Import "SDL3/src/video/windows/SDL_windowsgameinput.cpp"
Import "SDL3/src/video/windows/SDL_windowskeyboard.c"
Import "SDL3/src/video/windows/SDL_windowsmessagebox.c"
Import "SDL3/src/video/windows/SDL_windowsmodes.c"
Import "SDL3/src/video/windows/SDL_windowsmouse.c"
Import "SDL3/src/video/windows/SDL_windowsopengl.c"
Import "SDL3/src/video/windows/SDL_windowsopengles.c"
Import "SDL3/src/video/windows/SDL_windowsrawinput.c"
Import "SDL3/src/video/windows/SDL_windowsshape.c"
Import "SDL3/src/video/windows/SDL_windowsvideo.c"
Import "SDL3/src/video/windows/SDL_windowsvulkan.c"
Import "SDL3/src/video/windows/SDL_windowswindow.c"
?

?macos And Not ios
Import "SDL3/src/audio/coreaudio/SDL_coreaudio.m"
Import "SDL3/src/haptic/darwin/SDL_syshaptic.c"
Import "SDL3/src/hidapi/mac/hid.c"
Import "SDL3/src/joystick/darwin/SDL_iokitjoystick.c"
Import "SDL3/src/locale/macos/SDL_syslocale.m"
Import "SDL3/src/misc/macos/SDL_sysurl.m"
Import "SDL3/src/power/macos/SDL_syspower.c"
Import "SDL3/src/render/metal/SDL_render_metal.m"
Import "SDL3/src/sensor/coremotion/SDL_coremotionsensor.m"
Import "SDL3/src/tray/cocoa/SDL_tray.m"

Import "SDL3/src/video/cocoa/SDL_cocoaclipboard.m"
Import "SDL3/src/video/cocoa/SDL_cocoaevents.m"
Import "SDL3/src/video/cocoa/SDL_cocoakeyboard.m"
Import "SDL3/src/video/cocoa/SDL_cocoamessagebox.m"
Import "SDL3/src/video/cocoa/SDL_cocoametalview.m"
Import "SDL3/src/video/cocoa/SDL_cocoamodes.m"
Import "SDL3/src/video/cocoa/SDL_cocoamouse.m"
Import "SDL3/src/video/cocoa/SDL_cocoaopengl.m"
Import "SDL3/src/video/cocoa/SDL_cocoaopengles.m"
Import "SDL3/src/video/cocoa/SDL_cocoapen.m"
Import "SDL3/src/video/cocoa/SDL_cocoashape.m"
Import "SDL3/src/video/cocoa/SDL_cocoavulkan.m"
?

?ios
Import "SDL3/src/misc/ios/SDL_sysurl.m"
Import "SDL3/src/hidapi/ios/hid.m"
Import "SDL3/src/main/ios/SDL_sysmain_callbacks.m"

Import "SDL3/src/video/uikit/SDL_uikitappdelegate.m"
Import "SDL3/src/video/uikit/SDL_uikitclipboard.m"
Import "SDL3/src/video/uikit/SDL_uikitevents.m"
Import "SDL3/src/video/uikit/SDL_uikitmessagebox.m"
Import "SDL3/src/video/uikit/SDL_uikitmetalview.m"
Import "SDL3/src/video/uikit/SDL_uikitmodes.m"
Import "SDL3/src/video/uikit/SDL_uikitopengles.m"
Import "SDL3/src/video/uikit/SDL_uikitopenglview.m"
Import "SDL3/src/video/uikit/SDL_uikitpen.m"
Import "SDL3/src/video/uikit/SDL_uikitvideo.m"
Import "SDL3/src/video/uikit/SDL_uikitview.m"
Import "SDL3/src/video/uikit/SDL_uikitviewcontroller.m"
Import "SDL3/src/video/uikit/SDL_uikitvulkan.m"
Import "SDL3/src/video/uikit/SDL_uikitwindow.m"
?

?android

Import "SDL3/src/camera/android/SDL_camera_android.c"
Import "SDL3/src/core/android/SDL_android.c"
Import "SDL3/src/dialog/android/SDL_androiddialog.c"
Import "SDL3/src/filesystem/android/SDL_sysfilesystem.c"
Import "SDL3/src/haptic/android/SDL_syshaptic.c"
Import "SDL3/src/joystick/android/SDL_sysjoystick.c"
Import "SDL3/src/locale/android/SDL_syslocale.c"
Import "SDL3/src/misc/android/SDL_sysurl.c"
Import "SDL3/src/power/android/SDL_syspower.c"
Import "SDL3/src/sensor/android/SDL_androidsensor.c"

Import "SDL3/src/video/android/SDL_androidclipboard.c"
Import "SDL3/src/video/android/SDL_androidevents.c"
Import "SDL3/src/video/android/SDL_androidgl.c"
Import "SDL3/src/video/android/SDL_androidkeyboard.c"
Import "SDL3/src/video/android/SDL_androidmessagebox.c"
Import "SDL3/src/video/android/SDL_androidmouse.c"
Import "SDL3/src/video/android/SDL_androidpen.c"
Import "SDL3/src/video/android/SDL_androidtouch.c"
Import "SDL3/src/video/android/SDL_androidvideo.c"
Import "SDL3/src/video/android/SDL_androidvulkan.c"
Import "SDL3/src/video/android/SDL_androidwindow.c"
?

?haiku
Import "SDL3/src/power/haiku/SDL_syspower.c"
Import "SDL3/src/timer/haiku/SDL_systimer.c"
?
